In [3]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer


In [4]:
vectorizer = CountVectorizer()

In [5]:
docs = np.array(['Mirabai has won a silver medal in weightlifting in Tokyo olympics 2021',
                 'Sindhu has won a bronze medal in badminton in Tokyo olympics',
                 'Indian hockey team is in top four team in Tokyo olympics 2021 after 40 years'])

In [6]:
bag = vectorizer.fit_transform(docs)

In [7]:
print(vectorizer.vocabulary_)

{'mirabai': 12, 'has': 6, 'won': 20, 'silver': 14, 'medal': 11, 'in': 8, 'weightlifting': 19, 'tokyo': 17, 'olympics': 13, '2021': 0, 'sindhu': 15, 'bronze': 4, 'badminton': 3, 'indian': 9, 'hockey': 7, 'team': 16, 'is': 10, 'top': 18, 'four': 5, 'after': 2, '40': 1, 'years': 21}


In [8]:
print(bag.toarray())

[[1 0 0 0 0 0 1 0 2 0 0 1 1 1 1 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 1 0 2 0 0 1 0 1 0 1 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 1 2 1 1 0 0 1 0 0 2 1 1 0 0 1]]


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
corpus = [
    'This is the first document.',
     'This document is the second document.',
   'And this is the third one.',
     'Is this the first document?',
 ]


In [11]:
vectorizer = TfidfVectorizer()

In [12]:
X = vectorizer.fit_transform(corpus)

In [13]:
X.todense()

matrix([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
         0.        , 0.38408524, 0.        , 0.38408524],
        [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
         0.53864762, 0.28108867, 0.        , 0.28108867],
        [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
         0.        , 0.26710379, 0.51184851, 0.26710379],
        [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
         0.        , 0.38408524, 0.        , 0.38408524]])

In [14]:
from gensim.models import word2vec

In [15]:
corpus = [
          'Text of the first document.',
          'Text of the second document made longer.',
          'Number three.',
          'This is number four.',
]


In [17]:
tokenized_sentences = [sentence.split() for sentence in corpus]

In [18]:
model = word2vec.Word2Vec(tokenized_sentences, min_count=1)

In [19]:
model.wv.most_similar(positive=["document"])

[('Text', 0.17272792756557465),
 ('is', 0.16694682836532593),
 ('three.', 0.11117952316999435),
 ('made', 0.10941851139068604),
 ('the', 0.079634889960289),
 ('four.', 0.04130807891488075),
 ('Number', 0.037712957710027695),
 ('of', 0.00831594504415989),
 ('number', -0.005896794609725475),
 ('second', -0.03030233271420002)]